# https://stevenvanbael.com/profiling-zsh-startup
# zmodload zsh/zprof

export GREP_OPTIONS="-s --color=auto --exclude-dir=node_modules --exclude-dir=.env --exclude-dir=.git --exclude-dir=.svn --exclude-dir=.Trash --exclude-dir=.ropeproject"

export LESS="-R"
export LESSCHARSET="utf-8"

setopt autocd

for f in ~/.dotkyl/lib/*.zsh; do . $f; done

# If I move this to lib/installed, it will reappear here on upgrade
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# uncomment for profiling startup
# zprof
