# configure --> https://starship.rs/config
# find nerdfont unicode points --> https://www.nerdfonts.com/cheat-sheet
#     

palette = "dark"
add_newline = true
command_timeout = 1_000
format = """
${custom.pwd}\
${custom.vim_mode}\
$python\
$nodejs\
$kubernetes\
${custom.etc_host}\
$jobs\
${custom.mail}\
${custom.left_end}\
$fill\
${custom.fun}\
$fill\
${custom.right_start}\
$status\
$cmd_duration\
$git_branch\
$git_status\
$time\
$line_break\
$character
"""

[character]
    success_symbol = " [❧](fg:green)"
    error_symbol = " [❧](fg:red)"
    vimcmd_symbol = " [󰵵](fg:bright-blue)"

[cmd_duration]
    disabled = false
    show_notifications = false
    style = "fg:red bg:yellow"
    format = "[](bg:separator fg:yellow)[ $duration ]($style)[](bg:yellow fg:separator)"
    min_time = 1_000

[custom.etc_host]
    description = "Shows if oreilly.[com|review] is in /etc/hosts"
    command = 'grep -oE "oreilly\.(com|review)" /etc/hosts | uniq | sed s/\n//g | sed s/oreilly//g'
    when = 'grep -qE "oreilly\.(com|review)" /etc/hosts'
    symbol = "󰾋"
    style = "bg:blue fg:bright-white"
    format = "[](bg:blue fg:separator)[ $symbol $output ]($style)[](bg:separator fg:blue)"

[custom.fun]
    description = "A fun seasonal symbol"
    # command = "echo $(jot -b '🦆' -s '' $(jot -r 1 1 5))" # random numebr of ducks
    command = "echo 🦆 $(jot -b '-' -s '' $(jot -r 1 1 20))" # moving duck (moves left only)
    style = "bg:cyan fg:cyan"
    format = "[$output]($style)"
    when = true

[custom.left_end]
    description = "End of the left side of the prompt"
    style = "bg:cyan"
    format = "[](bg:cyan fg:separator)"
    when = true

[custom.mail]
    symbol = "📧"
    description = "Shows a mail icon if there is any mail, otherwise nothing."
    when = "mail -e"
    style = "bg:blue"
    format = "[](bg:blue fg:separator)[ $symbol$number ]($style)[](bg:separator fg:blue)"

[custom.pwd]
    # from env var set in precmd_functions in 090-prompt.zsh
    command = "echo $MYPWD"
    description = "Shows current directory's bookmark if there is one, otherwise a middle-truncated path to the current directory."
    when = true
    format = "[](fg:cyan)[$output ](fg:black bg:cyan)[](bg:separator fg:cyan)"

[custom.right_start]
    description = "Start of the right side of the prompt"
    style = "bg:cyan"
    format = "[](bg:cyan fg:separator)"
    when = true

[custom.vim_mode]
    # from env var set 020-keybindings.zsh
    command = "echo $VIM_MODE"
    description = "Shows the current mode for zsh vi mode."
    style = "bg:yellow fg:black"
    when = ''' test "$VIM_MODE" = "NORM" '''
    format = "[](bg:yellow fg:separator)[ $output ]($style)[](bg:separator fg:yellow)"

[fill]
    symbol = " "
    style = "bg:cyan"

[git_branch]
    disabled = false
    style = "bg:green fg:black"
    format = "[](bg:separator fg:green)[ $symbol$branch(:$remote_branch) ]($style)[](bg:green fg:separator)"

[git_status]
    disabled = false
    style = "bold bg:purple fg:green"
    format = '[](bg:separator fg:purple)[ $all_status$ahead_behind ]($style)[](bg:purple fg:separator)'
    ahead = "${count}↑"
    behind = "${count}↓"
    diverged = "${ahead_count}⇅ ${behind_count}"
    untracked = "፧ "
    up_to_date = "✓"
    stashed = "ᛋ "
    modified = "✽ "
    staged = "✚ "
    renamed = "⥱ "
    deleted = "✗ "

[jobs]
    style = "bg:yellow fg:red"
    format = "[](bg:yellow fg:separator)[ $symbol$number ]($style)[](bg:separator fg:yellow)"

[kubernetes]
    disabled = false
    symbol = "⎈ "
    style = "bold bg:purple fg:green"
    format = '[](bg:purple fg:separator)[ $symbol$context(:$namespace) ]($style)[](bg:separator fg:purple)'

[nodejs]
    symbol = "\ue781 "
    style = "bg:green fg:black"
    not_capable_style = "bg:green fg:red"
    format = "[](bg:green fg:separator)[ $symbol($version) ]($style)[](bg:separator fg:green)"
    version_format = "${raw}"

[python]
    symbol = "\ue606 "
    style = "fg:black bg:green"
    format = '[](bg:green fg:separator)[ ${symbol}${pyenv_prefix}(${version})([ $virtualenv](fg:red bg:green)) ]($style)[](bg:separator fg:green)'
    version_format = "${raw}"

[status]
    disabled = false
    style = "bg:red fg:bright-white"
    format = "[](bg:separator fg:red)[ $symbol $status ]($style)[](bg:red fg:separator)"

[time]
    disabled = false
    style = "bg:cyan fg:black"
    format = "[](bg:separator fg:cyan)[ $time ]($style)[](fg:cyan)"

[palettes.dark]
separator = "#444444"

[palettes.light]
separator = "#c8c8c8"
