# configure --> https://starship.rs/config
# find nerdfont unicode points --> https://www.nerdfonts.com/cheat-sheet
#     

palette = "dark"
add_newline = true
command_timeout = 1_000
format = """
${custom.pwd}\
${custom.vim_mode}\
$python\
$nodejs\
$kubernetes\
${custom.etc_host}\
$jobs\
${custom.mail}\
${custom.left_end}\
$fill\
${custom.fun}\
$fill\
${custom.right_start}\
$status\
$cmd_duration\
$git_branch\
$git_status\
$time\
$line_break\
$character
"""

[character]
    success_symbol = " [❧](fg:green)"
    error_symbol = " [❧](fg:red)"
    vimcmd_symbol = " [󰵵](fg:bright-blue)"

[cmd_duration]
    disabled = false
    show_notifications = false
    style = "fg:red bg:alert"
    format = "[](bg:separator fg:alert)[ $duration ]($style)[](bg:alert fg:separator)"
    min_time = 1_000

[custom.etc_host]
    description = "Shows if oreilly.[com|review] is in /etc/hosts"
    command = 'grep -oE "oreilly\.(com|review)" /etc/hosts | uniq | sed s/\n//g | sed s/oreilly//g'
    when = 'grep -qE "oreilly\.(com|review)" /etc/hosts'
    symbol = "󰾋"
    style = "bg:note fg:bright-white"
    format = "[](bg:note fg:separator)[ $symbol $output ]($style)[](bg:separator fg:note)"

[custom.fun]
    description = "A fun seasonal symbol"
    # command = "echo $(jot -b '🦆' -s '' $(jot -r 1 1 5))" # random numebr of ducks
    command = "echo 🦆 $(jot -b '-' -s '' $(jot -r 1 1 20))" # moving duck (moves left only)
    style = "bg:frame fg:frame"
    format = "[$output]($style)"
    when = true

[custom.left_end]
    description = "End of the left side of the prompt"
    style = "bg:frame"
    format = "[](bg:frame fg:separator)"
    when = true

[custom.mail]
    symbol = "📧"
    description = "Shows a mail icon if there is any mail, otherwise nothing."
    when = "mail -e"
    style = "bg:note"
    format = "[](bg:note fg:separator)[ $symbol$number ]($style)[](bg:separator fg:note)"

[custom.pwd]
    # from env var set in precmd_functions in 090-prompt.zsh
    command = "echo $MYPWD"
    description = "Shows current directory's bookmark if there is one, otherwise a middle-truncated path to the current directory."
    when = true
    format = "[](fg:frame)[$output ](fg:black bg:frame)[](bg:separator fg:frame)"

[custom.right_start]
    description = "Start of the right side of the prompt"
    style = "bg:frame"
    format = "[](bg:frame fg:separator)"
    when = true

[custom.vim_mode]
    # from env var set 020-keybindings.zsh
    command = "echo $VIM_MODE"
    description = "Shows the current mode for zsh vi mode."
    style = "bg:alert fg:black"
    when = ''' test "$VIM_MODE" = "NORM" '''
    format = "[](bg:alert fg:separator)[ $output ]($style)[](bg:separator fg:alert)"

[fill]
    symbol = " "
    style = "bg:frame"

[git_branch]
    disabled = false
    style = "bg:lang fg:black"
    format = "[](bg:separator fg:lang)[ $symbol$branch(:$remote_branch) ]($style)[](bg:lang fg:separator)"

[git_status]
    disabled = false
    style = "bold bg:ctx fg:ctx_fg"
    format = '[](bg:separator fg:ctx)[ $all_status$ahead_behind ]($style)[](bg:ctx fg:separator)'
    ahead = "${count}↑"
    behind = "${count}↓"
    diverged = "${ahead_count}⇅ ${behind_count}"
    untracked = "፧ "
    up_to_date = "✓"
    stashed = "ᛋ "
    modified = "✽ "
    staged = "✚ "
    renamed = "⥱ "
    deleted = "✗ "

[jobs]
    style = "bg:alert fg:red"
    format = "[](bg:alert fg:separator)[ $symbol$number ]($style)[](bg:separator fg:alert)"

[kubernetes]
    disabled = false
    symbol = "⎈ "
    style = "bold bg:ctx fg:ctx_fg"
    format = '[](bg:ctx fg:separator)[ $symbol$context(:$namespace) ]($style)[](bg:separator fg:ctx)'

[nodejs]
    symbol = "\ue781 "
    style = "bg:lang fg:black"
    not_capable_style = "bg:lang fg:red"
    format = "[](bg:lang fg:separator)[ $symbol($version) ]($style)[](bg:separator fg:lang)"
    version_format = "${raw}"

[python]
    symbol = "\ue606 "
    style = "fg:black bg:lang"
    format = '[](bg:lang fg:separator)[ ${symbol}${pyenv_prefix}(${version})([ $virtualenv](fg:red bg:lang)) ]($style)[](bg:separator fg:lang)'
    version_format = "${raw}"

[status]
    disabled = false
    style = "bg:err fg:bright-white"
    format = "[](bg:separator fg:err)[ $symbol $status ]($style)[](bg:err fg:separator)"

[time]
    disabled = false
    style = "bg:frame fg:black"
    format = "[](bg:separator fg:frame)[ $time ]($style)[](fg:frame)"

[palettes.dark]
separator = "#444444"
frame = "cyan"
lang = "green"
ctx = "purple"
alert = "yellow"
note = "blue"
err = "red"
ctx_fg = "green"

[palettes.light]
separator = "#c8c8c8"
frame = "bright-cyan"
lang = "bright-green"
ctx = "bright-purple"
alert = "bright-yellow"
note = "bright-blue"
err = "bright-red"
ctx_fg = "white"
